apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    {{- include "web-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-ui.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/meta: {{ include (print $.Template.BasePath "/meta-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "web-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "web-ui.name" . }}
          image: "{{ include "web-ui.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: {{ .Values.probe.liveness.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: {{ .Values.probe.readiness.port }}
          envFrom:
            - configMapRef:
                name: {{ include "web-ui.fullname" . }}
            - secretRef:
                name: {{ include "web-ui.fullname" . }}
          volumeMounts:
            - name: meta
              mountPath: /usr/share/nginx/html/meta
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: meta
          configMap:
            name: {{ include "web-ui.fullname" . }}-meta
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
