{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-cluster-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
{{- end }}
